version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_networks

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_networks
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/MovingCompany

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app_networks
    depends_on:
      - backend

networks:
  app_networks:
    driver: bridge



